modLoader="javafml" #mandatory
loaderVersion="[43,)" #mandatory
license="MIT"
issueTrackerURL="https://github.com/ChiefArug/markcraft/issues" #optional
[[mods]] #mandatory
modId="markcraft" #mandatory
version="1.2.1" #mandatory
displayName="MarkCraft" #mandatory
displayURL="https://www.curseforge.com/minecraft/mc-mods/markcraft/" #optional
logoFile="pack.png" #optional
authors="ChiefArug" #optional
displayTest="IGNORE_SERVER_VERSION"
description='''
An implementation of Discord flavoured markdown in Minecraft!

Supports all standard formatting (**bold**, *italic*, ***bold-italic***, ~~strikethrough~~, ||obfuscated||, __underline__) as well as @mentions and any combination of those.
It also has special support for colouring using backticks (`). `cThis text would be red`. The character after the first backtick determines the colour. See https://htmlcolorcodes.com/minecraft-color-codes/ for all characters.
'''
[[dependencies.markcraft]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[43,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.markcraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
